title: "&8-=( &7Ajustes &8)=-"
rows: 1
sound: ITEM_BOOK_PAGE_TURN

options:
  shields:
    name: "&6Escudos&8: &2%kingdoms_shield_time_left%"
    material: SHIELD
    lore:
      - "&7Compra escudos para tu Nación"
      - "para proegerlo contra invasores."
    posx: 1
    posy: 1
  invites:
    name: "&6Invitaciones&8: %invites%"
    material: BOOK
    lore:
      - "&7Cuando se deshabilita esto"
      - "cualquiera podra entrar al Reino sin"
      - "utilizar &2/k nation join %kingdoms_nation%"
    posx: 2
    posy: 1
  relations:
    name: "&6Relaciones"
    material: WRITABLE_BOOK
    lore:
      - "&7Cambia los atributos de tu"
      - "relacion con/por otras Naciones."
    posx: 3
    posy: 1
  tax:
    name: "&6Impuestos"
    material: PAPER
    lore:
      - "&7Cambie los impuestos de su"
      - "Nación por reinos. "
      - ""
      - "&6Impuesto&8: &2$%kingdoms_fancy_nation_tax%"
      - "&6Ecuación&8: &2%tax_equation%"
      - ""
      - "&6Impuesto de facturación&8: &2$%kingdoms_fancy_server_nation_tax%"
    posx: 4
    posy: 1

  back:
    name: "&2Volver"
    material: PLAYER_HEAD
    sound: default
    skull: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzQxMzNmNmFjM2JlMmUyNDk5YTc4NGVmYWRjZmZmZWI5YWNlMDI1YzM2NDZhZGE2N2YzNDE0ZTVlZjMzOTQifX19"
    lore:
      - "&6Regresar al menú nexus."
    posx: 9
    posy: 1