title: "&8-=( &2Configuración de campeón &8)=-"
type: HOPPER
sound: ITEM_ARMOR_EQUIP_DIAMOND

options:
  upgrade:
    name: "&bMejora de Equipamiento."
    material: DIAMOND_CHESTPLATE
    sounds:
      max-level: BLOCK_NOTE_BLOCK_BASS
      not-enough-resource-points: BLOCK_NOTE_BLOCK_BASS
      upgraded: ENTITY_EXPERIENCE_ORB_PICKUP
    lore:
      - "&7Mejora el arma y armadura"
      - "de tu campeón en cada mejora."
      - ""
      - "&2Nivel&8: &6%level%"
      - "&2Costo&8: &6%cost%"
    slot: 0
  change:
    name: "&6Cambiar"
    material: DIAMOND_SWORD
    lore:
      - "&7Cambia tu tipo de campeón."
    slot: 1

  back:
    name: "&2Volver"
    material: BARRIER
    lore:
      - "&6Vuelve a las mejores de campeón."
    slot: 4